platform :ios, '10.0'
use_frameworks!

target 'MPUtils_Example' do
  pod 'MPUtils', :path => '../'

  target 'MPUtils_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end

end
