osx_image: xcode10
language: objective-c

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MPUtils.xcworkspace -scheme MPUtils-Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO | xcpretty
