osx_image: xcode10
language: objective-c

script:
- set -o pipefail && xcodebuild clean build test -enableCodeCoverage YES -workspace Example/MPUtils.xcworkspace -scheme MPUtils-Example -sdk iphonesimulator12.0 ONLY_ACTIVE_ARCH=NO-destination 'platform=iOS Simulator,name=iPhone 8,OS=12.0' | xcpretty
