name: SwiftLint

on: [pull_request, push]

jobs:
  SwiftLint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@3.1.0
