name: Tests

on: [push]

jobs:
  build:

    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild test -scheme "MPUtils-Package" -enableCodeCoverage "YES" -destination "platform=iOS Simulator,OS=13.3,name=iPhone 11" | xcpretty
