name: Tests

on: [push]

jobs:
  build:

    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Xcode
      run: xcode-select --install
    - name: Run tests
      run: swift test
