name: Tests

on: [push]

jobs:
  build:

    runs-on: [macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: xcodebuild -quiet -scheme "MPUtils-Package" test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11' -enableCodeCoverage YES | xcpretty
