name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Swift
      run: |
        tar xzf swift-5.1.3-RELEASE-ubuntu18.04.tar.gz
        echo "::add-path::$(pwd)/swift-5.1.3-RELEASE-ubuntu18.04/usr/bin"
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
